### ISSUE TITLE
No out-of-sync warning/restart

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome-daily-status-bot#4]
If the bot is connected to a node that get out-of-sync and stops sending new block events, the bot just waits. No warnings.

If #3 is implemented, a solution would involve:

- The process is initiated with `forever` through the standard `start` npm script.
- If no new block events are received after a predefined timeout is reached, the process exits and `forever` automatically restarts it creating a new connection (eventually to a different node).

**Comment by ndelvalle** [comment]
Resolved in commit 5b8d92447268fc04f6fc64c426a076d7085f3a2f
