### ISSUE TITLE
Shall debounce heartbeat processing

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome-daily-status-bot#5]
New block events could be received in bursts. In that case, only the first one is important to trigger the heartbeat processing. All others shall be discarded (debounced) until the initial processing is finished.

A lib that can help in this is: https://github.com/autonomoussoftware/ethereum-blockchain-indexer/blob/develop/lib/promise-lead-debounce/index.js

**Comment by ndelvalle** [comment]
Resolved in commit [5b8d92447268fc04f6fc64c426a076d7085f3a2f](https://github.com/autonomoussoftware/metronome-daily-status-bot/commit/5b8d92447268fc04f6fc64c426a076d7085f3a2f)
