### ISSUE TITLE
ETC Chain Auction Bot

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome-daily-status-bot#9]
Will need to have separate tweet for the MET auctions on Ethereum Classic.

**Comment by gabmontes** [comment]
@Dareknotderek will the ETC auctions be tweeted by a different Twitter account?

**Comment by Dareknotderek** [comment]
@gabmontes Doesn't need to be - probably shouldn't be. Is that okay? Just have the one account tweet ETH and ETC (and others in the future) auctions?

**Comment by Dareknotderek** [comment]
Might be worth considering what one tweet with multiple auction info looks like? per Jeff

**Comment by Dareknotderek** [comment]
@gabmontes, @patidarmanoj10 suggests two tweets  1) first tweet -  when one auction sold out  and other still open .  info like chain 1:  closing price  details . Chain 2:  current available met  and current price 2) second tweet when both sold.
